spring.application.name=SafePass
spring.datasource.url=jdbc:mysql://localhost:3306/SafePass
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_USER}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
